import type { IndustryPluginManifest } from '@/core/industry/pluginTypes';
import { withNoticesTabs } from '@/core/industry/pluginTypes';

/** 피아노학원 플러그인 매니페스트 (풀 기능) */
export const pianoPluginManifest: IndustryPluginManifest = {
  id: 'piano',
  option: {
    value: 'piano',
    label: '피아노학원',
    description: '원생·출결·수강료·교재 중심 운영',
  },
  theme: 'indigo',
  accent: {
    btn: 'bg-indigo-600',
    btnHover: 'hover:bg-indigo-700',
    icon: 'text-indigo-600',
    hoverBg: 'hover:bg-indigo-50',
    ring: 'focus:ring-indigo-500 focus:border-indigo-300',
  },
  attendanceDefault: true,
  usesClassBasedSchedule: true,
  customerListTab: 'students',
  showSchoolFields: true,
  showPickupFields: false,
  levelLabel: '레벨',
  adminTabs: withNoticesTabs([
    'dashboard',
    'students',
    'parents',
    'classes',
    'timetable',
    'attendance',
    'makeups',
    'lessons',
    'practice',
    'consultations',
    'resources',
    'tuition',
    'unpaid',
    'textbooks',
    'teachers',
    'calendar',
    'recitals',
    'settings',
    'curriculum',
    'assignments',
    'achievements',
    'reports',
  ]),
  staffTabs: withNoticesTabs([
    'dashboard',
    'students',
    'timetable',
    'attendance',
    'makeups',
    'lessons',
    'practice',
    'consultations',
    'calendar',
    'recitals',
    'curriculum',
    'assignments',
    'achievements',
    'reports',
  ]),
};
